//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class bible_book_name
    {
        public int bid { get; set; }
        public int bkid { get; set; }
        public string book { get; set; }
        public string fname { get; set; }
        public string sname { get; set; }
        public int chap { get; set; }
    }
}
