//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class bible_context
    {
        public int vsid { get; set; }
        public int bid { get; set; }
        public string book { get; set; }
        public int chapter { get; set; }
        public int verse { get; set; }
        public string linemark { get; set; }
        public string context { get; set; }
    }
}
