//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ClassID { get; set; }
        public int LessonID { get; set; }
        public int Day { get; set; }
        public int QuestionID { get; set; }
        public string Question1 { get; set; }
        public string Answer { get; set; }
        public string Quotes { get; set; }
    }
}
