//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userid { get; set; }
        public string first_name_eng { get; set; }
        public string first_Name_chn { get; set; }
        public string last_Name_eng { get; set; }
        public string last_Name_chn { get; set; }
        public string address_1 { get; set; }
        public string address_2 { get; set; }
        public string address_3 { get; set; }
        public string city { get; set; }
        public string state_province { get; set; }
        public string email { get; set; }
        public string home_phone { get; set; }
        public string cell_phone { get; set; }
        public Nullable<int> age { get; set; }
        public string occupation { get; set; }
        public string marital_staus { get; set; }
        public string spouse { get; set; }
        public string contact_person { get; set; }
        public string contact_phone { get; set; }
        public string contact_relationship { get; set; }
        public string health_issue { get; set; }
        public string medical_training { get; set; }
        public string can_provide_medical_assitance { get; set; }
        public string child_name { get; set; }
        public Nullable<int> child_age { get; set; }
        public string child_school_year { get; set; }
        public string parent_child_BSF { get; set; }
        public string affiliated_church { get; set; }
        public string church_address { get; set; }
        public string church_member { get; set; }
        public string church_fellowship { get; set; }
        public string bible_knowledge { get; set; }
        public string highest_level_BSF_class { get; set; }
        public string prefer_language { get; set; }
        public string prefer_location { get; set; }
        public Nullable<int> prefer_BSF_note { get; set; }
        public string mother_baby_helper { get; set; }
        public string prior_BSF_class { get; set; }
        public Nullable<long> BSF_class_completed { get; set; }
        public string referrer { get; set; }
        public System.DateTime registration_datetime { get; set; }
        public Nullable<System.DateTime> approve_datetime { get; set; }
        public Nullable<System.DateTime> last_change_datetime { get; set; }
        public string status { get; set; }
    }
}
